# Generated by Django 5.2.1 on 2025-11-11 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email адрес"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="фамилия")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        max_length=15,
                        verbose_name="пол",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(default=30, verbose_name="возраст"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                ("hobbies", models.TextField(blank=True, verbose_name="увлечения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("single", "В поиске"),
                            ("relationship", "В отношениях"),
                            ("married", "Женат/Замужем"),
                        ],
                        default="single",
                        max_length=50,
                        verbose_name="статус отношений",
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество лайков"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False, verbose_name="приватный профиль"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="телефон"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="верифицирован"),
                ),
                (
                    "last_active",
                    models.DateTimeField(
                        auto_now=True, verbose_name="последняя активность"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invitation_type",
                    models.CharField(
                        choices=[
                            ("randezvous", "Свидание"),
                            ("contact", "Обмен контактами"),
                        ],
                        max_length=30,
                        verbose_name="тип приглашения",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="сообщение")),
                (
                    "proposed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="предлагаемая дата"
                    ),
                ),
                (
                    "proposed_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="предлагаемое место"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="от пользователя",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователю",
                    ),
                ),
            ],
            options={
                "verbose_name": "приглашение",
                "verbose_name_plural": "приглашения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user1_contact_shared",
                    models.BooleanField(
                        default=False, verbose_name="пользователь 1 поделился"
                    ),
                ),
                (
                    "user2_contact_shared",
                    models.BooleanField(
                        default=False, verbose_name="пользователь 2 поделился"
                    ),
                ),
                (
                    "user1_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="телефон пользователя 1"
                    ),
                ),
                (
                    "user2_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="телефон пользователя 2"
                    ),
                ),
                (
                    "exchanged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата обмена"
                    ),
                ),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.invitation",
                        verbose_name="приглашение",
                    ),
                ),
            ],
            options={
                "verbose_name": "обмен контактами",
                "verbose_name_plural": "обмены контактами",
            },
        ),
        migrations.CreateModel(
            name="UserPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_photos/",
                        verbose_name="фотография",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="главная фотография"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата загрузки"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "фотография пользователя",
                "verbose_name_plural": "фотографии пользователей",
                "ordering": ["-is_main", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата совпадения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активно"),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь 1",
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "совпадение",
                "verbose_name_plural": "совпадения",
                "ordering": ["-created_at"],
                "unique_together": {("user1", "user2")},
            },
        ),
        migrations.CreateModel(
            name="UserAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view", "Просмотр"),
                            ("like", "Лайк"),
                            ("dislike", "Дизлайк"),
                        ],
                        max_length=20,
                        verbose_name="тип действия",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата действия"
                    ),
                ),
                (
                    "user_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="от пользователя",
                    ),
                ),
                (
                    "user_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователю",
                    ),
                ),
            ],
            options={
                "verbose_name": "действие пользователя",
                "verbose_name_plural": "действия пользователей",
                "ordering": ["-created_at"],
                "unique_together": {("user_from", "user_to", "action_type")},
            },
        ),
    ]
