# Generated by Django 5.2.1 on 2025-11-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraction',
            unique_together={('user_from', 'user_to')},
        ),
    ]
